meteo-0.3.1.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1374,7 +1374,7 @@ fi
 
 PACKAGE=meteo
 
-VERSION=0.3.0
+VERSION=0.3.1
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:1380: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -7993,7 +7993,7 @@ if test "${with_html_dir+set}" = set; then
 fi;
 HTMLDIR="${with_html_dir}"
 
-ac_config_files="$ac_config_files Makefile include/Makefile lib/Makefile src/Makefile support/Makefile conf/Makefile doc/Makefile html/Makefile browser/Makefile db/Makefile man/Makefile man/meteo.1 html/meteo.html"
+ac_config_files="$ac_config_files Makefile include/Makefile lib/Makefile src/Makefile support/Makefile conf/Makefile doc/Makefile html/Makefile browser/Makefile browser/po/Makefile db/Makefile man/Makefile man/meteo.1 html/meteo.html"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -8319,13 +8319,14 @@ do
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "html/Makefile" ) CONFIG_FILES="$CONFIG_FILES html/Makefile" ;;
   "browser/Makefile" ) CONFIG_FILES="$CONFIG_FILES browser/Makefile" ;;
+  "browser/po/Makefile" ) CONFIG_FILES="$CONFIG_FILES browser/po/Makefile" ;;
   "db/Makefile" ) CONFIG_FILES="$CONFIG_FILES db/Makefile" ;;
   "man/Makefile" ) CONFIG_FILES="$CONFIG_FILES man/Makefile" ;;
   "man/meteo.1" ) CONFIG_FILES="$CONFIG_FILES man/meteo.1" ;;
   "html/meteo.html" ) CONFIG_FILES="$CONFIG_FILES html/meteo.html" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:8328: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8329: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8567,7 +8568,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8570: creating $ac_file" >&5
+    { echo "$as_me:8571: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8585,7 +8586,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8588: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8589: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8598,7 +8599,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8601: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8602: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8659,7 +8660,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8662: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8663: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8670,7 +8671,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8673: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8674: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8683,7 +8684,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8686: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8687: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8800,7 +8801,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8803: $ac_file is unchanged" >&5
+      { echo "$as_me:8804: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
